Do work inside of a temporary directory

diff --git a/pgbackup b/pgbackup
--- a/pgbackup
+++ b/pgbackup
@@ -53,6 +53,13 @@ if [ ! -f ~/.s3cfg ]; then
     exit 2
 fi
 
+WORKDIR=$(mktemp -d) || { \
+    echo >&2 "Could not create a temporary directory."; exit 1; \
+}
+
+cd /tmp
+cd "$WORKDIR"
+
 for db in "${DBS[@]}"; do
     echo "Backing up database: ${db}."
 
@@ -86,3 +93,6 @@ for db in "${DBS[@]}"; do
 
     rm "${db}.sql.gz.gpg"
 done
+
+cd ../
+rmdir "$WORKDIR"
